med-app/models/appointments.py
from extensions import db
from sqlalchemy import TIMESTAMP
from datetime import datetime


class Appointment(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    date = db.Column(db.Date(), nullable=False)
    time = db.Column(db.String(10), nullable=False)
    status = db.Column(db.String(100), nullable=False, default='pending')
    comment = db.Column(db.String(255), nullable=True)
    patient_id = db.Column(db.Integer, db.ForeignKey('patient.id'), nullable=False)
    doctor_id = db.Column(db.Integer, db.ForeignKey('doctor.id'), nullable=False)
    created_at = db.Column(TIMESTAMP, default=datetime.utcnow, nullable=False, )
    active = db.Column(db.Boolean())

    def __str__(self):
        return f"{self.date} {self.time}"

    def __init__(self, date, time, doctor_id, patient_id, status, comment, active=1):
        self.date = date
        self.time = time
        self.doctor_id = doctor_id
        self.patient_id = patient_id
        self.status = status
        self.comment = comment
        self.active = active

med-app/models/doctor.py
from extensions import db
from sqlalchemy import TIMESTAMP
from datetime import datetime

class Doctor(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    consultation_fee = db.Column(db.Numeric(10, 2), nullable=False, default=0.0)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    created_at = db.Column(TIMESTAMP, default=datetime.utcnow, nullable=False, )
    specialisation_id = db.Column(db.Integer, db.ForeignKey('specialisation.id'), nullable=False)
    prescriptions = db.relationship('Prescription', backref='doctor')
    appointments = db.relationship('Appointment', backref='doctor')
    active = db.Column(db.Boolean())
    def __init__(self, fee, user_id, spec_id, active=1):
        self.consultation_fee = fee
        self.user_id = user_id
        self.specialisation_id = spec_id
        self.active = active

med-app/models/prescription.py
from extensions import db
from sqlalchemy import TIMESTAMP
from datetime import datetime

class Prescription(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    prescription = db.Column(db.String(255), nullable=False)
    created_at = db.Column(TIMESTAMP, default=datetime.utcnow, nullable=False, )
    patient_id = db.Column(db.Integer, db.ForeignKey('patient.id'), nullable=False)
    doctor_id = db.Column(db.Integer, db.ForeignKey('doctor.id'), nullable=False)
    active = db.Column(db.Boolean())

    def __str__(self):
        return self.prescription

med-app/admin/routes.py
import os

from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import current_user, login_required, logout_user
from flask_security import roles_accepted, SQLAlchemyUserDatastore
from flask_security.utils import hash_password
from werkzeug.utils import secure_filename

import config
from extensions import db, SQLAlchemyError, OperationalError, bcrypt
from models.appointments import Appointment
from models.doctor import Doctor
from models.location import Location
from models.patient import Patient
from models.role import Role
from models.specialisation import Specialisation
from models.user import User

admin = Blueprint('admin', __name__, static_folder='../static', template_folder='../templates')
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}


@admin.route('/')
@roles_accepted('admin')
def admin_dash():
    user = current_user.username
    return render_template('admin/admin_home.html', username=user)


@admin.route('/add-specialisation')
@roles_accepted('admin')
def add_specialisation():
    return render_template('admin/add_specialisation.html')


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@admin.route('/save-specialisation', methods=['GET', 'POST'])
@roles_accepted('admin')
def save_specialisation():
    if request.method == "POST":
        # check if the post request has the file part
        if 'file' not in request.files:
            flash('No file part')
            return redirect(request.url)
        file = request.files['file']
        # If the user does not select a file, the browser submits an
        # empty file without a filename.
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            name = request.form.get('name')
            spec = Specialisation(name=name, img=filename)
            db.session.add(spec)
            file.save(os.path.join('static/uploads', filename))
            db.session.commit()
            return redirect(url_for("admin.get_spec"))

@admin.route('/appointments/<id>', methods=['GET', 'POST'])
@roles_accepted('admin')
def delete_appointment(id):
    app = Appointment.query.filter_by(id=id).update({"active":0})
    db.session.commit()
    flash("Appointment successfully deleted", "success text-center")
    return redirect(url_for("admin.get_appointments"))

@admin.route('/patient/<id>', methods=['GET', 'POST'])
@roles_accepted('admin')
def del_patient(id):
    usr = User.query.get(id)
    user = User.query.filter_by(id=id).update({"active":0})
    db.session.commit()
    flash(f"{usr} successfully deleted", "success text-center")
    return redirect(url_for("admin.get_patients"))

@admin.route('/doctor/<id>', methods=['GET', 'POST'])
@roles_accepted('admin')
def del_doctor(id):
    usr = User.query.get(id)
    user = User.query.filter_by(id=id).update({"active":0})
    db.session.commit()
    flash(f"{usr} successfully deleted", "success text-center")
    return redirect(url_for("admin.get_doctors"))


@admin.route('/add-doctor')
@roles_accepted('admin')
def add_doctor():
    specs = Specialisation.query.all()
    return render_template("admin/add_doctors.html", specs=specs)


@admin.route('/specialisations')
@roles_accepted('admin')
def get_spec():
    specs = Specialisation.query.all()
    return render_template("admin/specialisation.html", specs=specs)


user_datastore = SQLAlchemyUserDatastore(db, User, Role)


@admin.route('/save-doctor', methods=['GET', 'POST'])
@roles_accepted('admin')
def save_doctor():
    message = ""
    if request.method == "POST":
        username = request.form.get('username')
        email = request.form.get('email')
        password = request.form.get('password')
        password_confirm = request.form.get('password_confirm')
        if password.__ne__(password_confirm):
            flash("Password does not match Password confirmation. Please match the passwords.", "alert")
            return render_template("admin/add_doctors.html")
        phone = consultation_fee = request.form.get('phone')
        # DOCTOR
        spec = request.form.get('spec_id')
        consultation_fee = request.form.get('fee')

        # LOCATION
        street = request.form.get('street')
        city = request.form.get('city')
        country = request.form.get('country')

        doctor_role = Role(name='doctor')

        try:
            user = user_datastore.create_user(username=username, email=email, password=bcrypt.generate_password_hash(password)
                                              , phone=phone, roles=[doctor_role])
            db.session.add(user)
            db.session.commit()
            location = Location(street=street, city=city, country=country, user_id=user.id)
            doctor = Doctor(user_id=user.id, spec_id=spec, fee=consultation_fee)
            db.session.add(location)
            db.session.add(doctor)
        except SQLAlchemyError as e:
            flash(f"{str(e.__dict__['orig'])}", "danger text-center")
            db.session.rollback()
            return render_template("admin/add_doctors.html")
        except OperationalError as o:
            flash(f"{str(o.__dict__['orig'])}", "danger text-center")
            db.session.rollback()
            return render_template("admin/add_doctors.html")
        else:
            db.session.commit()

        flash("Successfully added new doctor", "success text-center m-2")
        return render_template('admin/manage_doctors.html')
    flash("Error encountered while adding new doctor! Please try again with valid information", "alert")
    return redirect("admin/manage_doctors.html")


@admin.route('/get-doctors', methods=['GET'])
@roles_accepted('admin')
def get_doctors():
    docs = Doctor.query.all()
    docs2 = []
    for doc in docs:
        user = User.query.get(doc.user_id)
        spec = Specialisation.query.get(doc.specialisation_id)
        doc = {"user": user, "spec": spec, "doc": doc}
        docs2.append(doc)
    return render_template("admin/manage_doctors.html", doctors=docs2)


@admin.route('/appointments', methods=['GET'])
@roles_accepted('admin')
def get_appointments():
    appointments = Appointment.query.all()
    appoints = []
    for app in appointments:
        pat = User.query.get(Patient.query.get(app.patient_id).user_id)
        doc = User.query.get(Doctor.query.get(app.doctor_id).user_id)
        spec = Specialisation.query.get(Doctor.query.get(app.doctor_id).specialisation_id)
        appointment = {"pat": pat, "spec": spec, "doc": doc, "status": app.status,
                       "date": app.date, "time": app.time, "id":app.id, "active":app.active}
        appoints.append(appointment)
    return render_template("admin/appointments.html", appointments=appoints)


@admin.route('/manage-patients', methods=['GET'])
@roles_accepted('admin')
def get_patients():
    patients = Patient.query.all()
    pats = []
    for pat in patients:
        user = User.query.get(pat.user_id)
        pat2 = {"user": user, "pat": pat}
        pats.append(pat2)
    return render_template("admin/manage_patients.html", patients=pats)


@admin.route('/logout', methods=['GET', 'POST'])
@login_required
def logout_():
    logout_user()
    return redirect(url_for("main.index"))



@admin.route('/profile', methods=['GET'])
@roles_accepted('admin')
def edit_profile():
    user_info = current_user
    return render_template('admin/profile.html', info=user_info)


@admin.route('/save-profile', methods=['POST', 'GET'])
@roles_accepted('admin')
def save_profile():
    username = request.form.get('username')
    email = request.form.get('email')
    try:
        user = User.query.filter_by(id=current_user.id).update({"username": username, "email": email})
    except SQLAlchemyError as e:
        flash(f"{str(e.__dict__['orig'])}", "alert text-center")
        db.session.rollback()
        redirect(url_for("patient.edit_profile"))
    except OperationalError as o:
        flash(f"{str(o.__dict__['orig'])}", "alert text-center")
        db.session.rollback()
        return redirect(url_for("admin.edit_profile"))
    else:
        db.session.commit()
    flash("Successfully edit user profile.", "success text-center")
    return redirect(url_for("admin.edit_profile"))


@admin.route('/change-password', methods=['POST', 'GET'])
@roles_accepted('admin')
def change_password():
    old_pwd = request.form.get('old_password')
    new_pwd = request.form.get('new_password')
    confirm_pwd = request.form.get('password_confirm')
    user = User.query.filter_by(id=current_user.id).first()
    if user and user.verify_password(old_pwd):
        if new_pwd.__ne__(confirm_pwd):
            flash("Password does not match Password confirmation. Please match the passwords.", "alert")
            return redirect(url_for("admin.edit_profile"))
        user = User.query.filter_by(id=current_user.id).update({"password": bcrypt.generate_password_hash(new_pwd)})
        db.session.commit()
        flash("Successfully change password!", "success text-center")
        return redirect(url_for("admin.edit_profile"))

med-app/doctor/routes.py
from datetime import date, datetime

from flask import  Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user
from flask_security import roles_accepted
from models.prescription import Prescription
from models.doctor import Doctor
from models.patient import Patient
from models.specialisation import Specialisation
from models.appointments import  Appointment
from models.location import Location
from models.user import User
from extensions import db, bcrypt, SQLAlchemyError, OperationalError

doc = Blueprint('doctor', __name__)


@doc.route('/')
@roles_accepted('doctor')
def doc_dash():
    user = current_user.username
    return render_template('doctor/dash_history.html', username=user)

@doc.route('/create-prescription/<patient_id>/<app_id>', methods=['GET'])
@roles_accepted('doctor')
def create_prescription(patient_id, app_id):
    todays_date = date.today()
    patient = Patient.query.get(patient_id)
    patient_info = User.query.get(patient.user_id)
    doc_info = current_user
    doc = Doctor.query.filter_by(user_id=current_user.id).first()
    doc_spec = Specialisation.query.get(doc.specialisation_id)
    age =todays_date.today() - patient.dob

    data = {"doc_info": current_user, "doc":doc, "patient": patient, "patient_info":patient_info,
            "spec": doc_spec, "patient_age":age, "app_id":app_id}
    return render_template('doctor/create_prescription.html', data=data)

@doc.route('/save-prescription', methods=['POST', 'GET'])
@roles_accepted('doctor')
def save_prescription():
    if request.method=="POST":
        doctor = Doctor.query.filter_by(user_id=current_user.id).first()
        patient_id = request.form.get("patient_id")
        appointment_id = request.form.get("appointment_id")
        prescription = request.form.get('prescription')
        prescription = Prescription(patient_id=patient_id, doctor_id=doctor.id, prescription=prescription)
        db.session.add(prescription)
        app_updated = Appointment.query.filter_by(id=appointment_id).update({"status": "approved"})
        db.session.commit()
        return redirect(url_for('doctor.prescriptions'))

@doc.route('/prescriptions', methods=['GET'])
@roles_accepted('doctor')
def prescriptions():
    prescriptions = Doctor.query.filter_by(user_id=current_user.id).first().prescriptions
    prescrips=[]
    for p in prescriptions:
        p_user = User.query.get(Patient.query.get(p.patient_id).user_id)
        presc = {"id":str(p.id), "patient":p_user, "created_at": p.created_at, "prescription": p.prescription}
        prescrips.append(presc)
    return render_template("doctor/prescriptions.html", prescriptions=prescrips)

@doc.route('/prescription/<id>', methods=['GET'])
@roles_accepted('doctor')
def prescription(id):
    prescription = Prescription.query.get(id)
    return render_template("doctor/prescription.html", presc=prescription)

@doc.route('/appointments-history', methods=['GET'])
@roles_accepted('doctor')
def appointments_history():
    doctor = Doctor.query.filter_by(user_id=current_user.id).first()
    # appointments = Appointment.query.filter(Appointment.patient_id==patient.id).all()
    appointments = []
    for appointment in doctor.appointments:
        patient = Patient.query.get(appointment.patient_id)
        user = User.query.get(patient.user_id)
        new_app = { "patient": patient, "user":user, "app":appointment}
        appointments.append(new_app)
    return render_template('doctor/appointments.html', appointments=appointments)

@doc.route('/profile', methods=['GET'])
@roles_accepted('doctor')
def edit_profile():
    user_info = current_user
    doc = Doctor.query.filter_by(user_id=current_user.id).first()
    spec = Specialisation.query.get(doc.specialisation_id)
    specs = Specialisation.query.all()
    data = {"user":user_info, "doc":doc, "spec":spec}
    return render_template('doctor/profile.html', info=data, specs=specs)


@doc.route('/change-password', methods=['POST', 'GET'])
@roles_accepted('doctor')
def change_password():
    old_pwd = request.form.get('old_password')
    new_pwd = request.form.get('new_password')
    confirm_pwd = request.form.get('password_confirm')
    user = User.query.filter_by(id=current_user.id).first()
    if user and user.verify_password(old_pwd):
        if new_pwd.__ne__(confirm_pwd):
            flash("Password does not match Password confirmation. Please match the passwords.", "alert")
            return redirect(url_for("doctor.edit_profile"))
        user = User.query.filter_by(id=current_user.id).update({"password": bcrypt.generate_password_hash(new_pwd)})
        db.session.commit()
        flash("Successfully change password!", "success text-center")
        return redirect(url_for("doctor.edit_profile"))


@doc.route('/save-profile', methods=['POST', 'GET'])
@roles_accepted('doctor')
def save_profile():
    username = request.form.get('username')
    email = request.form.get('email')
    phone = request.form.get('phone')
    dob = request.form.get('dob')
    sex = request.form.get('gender')
    street = request.form.get('street')
    city = request.form.get('city')
    country = request.form.get('country')
    try:
        user = User.query.filter_by(id=current_user.id).update({"username": username, "email": email, "phone": phone})
        location = Location.query.filter_by(user_id=current_user.id).update({"street": street, "city": city, "country": country})
    except SQLAlchemyError as e:
        flash(f"{str(e.__dict__['orig'])}", "alert text-center")
        db.session.rollback()
        redirect(url_for("doctor.edit_profile"))
    except OperationalError as o:
        flash(f"{str(o.__dict__['orig'])}", "alert text-center")
        db.session.rollback()
        return redirect(url_for("doctor.edit_profile"))
    else:
        db.session.commit()
    flash("Successfully edit user profile.", "success text-center")
    return redirect(url_for("doctor.edit_profile"))

med-app/templates/doctor/appointments.html
{% extends "doctor/dashboard.html"%}
{% block dashboard_content %}
     <div class="container">
        <div class="card  shadow-sm">
            <div class="card-body">
            <div class="container table-responsive pt-2 py-5">
            <table class="table table-striped table-hover text-13">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Patient</th>
                    <th scope="col">Gender</th>
                  <th scope="col">Date of Birth</th>
                  <th scope="col">Appointment Date & Time</th>
                     <th scope="col">Create At</th>
                     <th scope="col">Action</th>
                </tr>
              </thead>
              <tbody>
                {% for appointment in appointments %}
                <tr>
                  <th scope="row">#001</th>
                  <td>{{ appointment.user}}</td>
                    <td>{{ appointment.patient.gender}}</td>
                    <td>{{ appointment.patient.dob}}</td>
                    <td>{{ appointment.app.date }} {{ appointment.app.time }}</td>
                     <td>{{ appointment.app.created_at }}</td>
                  <td>
                       {% if appointment.app.status=="cancel" %}
                      <span class="badge bg-danger">Cancelled</span>
                            {% elif appointment.app.status=="approved" %}
                      <span class="badge bg-success">Approved</span>
                        {% elif appointment.app.status=="pending" %}
                      <span class="badge bg-orange">Pending</span>
                      {% else %}
                            <span class="badge bg-primary">{{ appointment.app.status }}</span>
                      {% endif %}
                  </td>
                  <td>
                      {% if appointment.app.status=="cancel" %}
                       <button disabled class="btn btn-sm btn-danger">cancelled</button>
                          {% elif appointment.app.status=="approved" %}
                       <button disabled class="btn btn-sm btn-success">DONE</button>
                      {% else %}
                            <a  class="btn btn-sm bg-blue text-white text-13"
                            href="{{url_for('doctor.create_prescription',
                            patient_id=appointment.patient.id, app_id=appointment.app.id) }}">Prescription Note</a>
                          <a class="btn btn-sm btn-danger text-13"
                         href="{{url_for('patient.cancel_appointment', id=appointment.app.id) }}">Cancel</a>
                      {% endif %}
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
            </div>
            </div>
        </div>
     </div>
{% endblock %}

med-app/templates/doctor/dashboard.html
{% extends "base.html" %}
{% block body %}
    <div class="main-wrap">
    <input id="slide-sidebar" type="checkbox" role="button" />
        <label for="slide-sidebar" class="toggle-label"><span class="fa-stack fa-md "><i class="fa fa-th-list fa-stack-1x "></i></span></label>
    <div class="sidebar position-fixed">
        <div class="container p-1 pb-2 pt-3">
            <h4 class="text-center heading text-orange font-weight9">
                <span class="fa-stack fa-md"><i class="fa fa-dashboard fa-stack-1x "></i></span>
                <span class="text-15">DASHBOARD</span>
            </h4>
        </div>
        <div class="container">
            <ul class="list-group list-unstyled text-13">
            <li class="list-group-item"><a class="navbar-link text-black" href="/doctor/prescriptions">
                 <span class="fa-stack fa-md "><i class="fa fa-book fa-stack-1x "></i></span>Prescriptions</a></li>
            <li class="list-group-item"><a class="navbar-link text-black" href="/doctor/appointments-history">
                 <span class="fa-stack fa-md "><i class="fa fa-history fa-stack-1x "></i></span>Appointments</a></li>
            <li class="list-group-item"><a class="navbar-link text-black" href="/doctor/profile">
                 <span class="fa-stack fa-md "><i class="fa fa-wrench fa-stack-1x "></i></span>My Profile</a>
            </li>
                <li class="list-group-item">
               <a href="#" class="navbar-link text-black">
                   <span class="fa-stack fa-md"><i class="fa fa-server fa-stack-1x "></i></span>Contact</a>
            </li>
        </ul>
        </div>
    </div>
    <div class="portfolio">
        <nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand text-orange font-weight9" href="#">HD & M</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse  " id="navbarNav">
                    <ul class="navbar-nav ms-auto font-weight6 text-14">
                        <li class="nav-item m-2 mr-3">
                          <a class="nav-link text-black" aria-current="page" href="#">
                          <i class="fa fa-home p-1 pr-2 text-15"></i>Home</a>
                        </li>
                        <li class="nav-item m-2 mr-3">
                          <a class="nav-link  pr-2 text-black" href="#"><i class="fa fa-info-circle p-1 pr-2 text-14"></i>About</a>
                        </li>
                        <li class="nav-item m-2 mr-3">
                            <a class="nav-link text-black" href="{{ url_for('admin.logout_') }}">
                                <i class="fa fa-sign-out p-1 pr-2 text-14"></i>Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="dashboard container">
           <div class="pt-2">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category,msg in messages %}
                        <div class="card bg-{{ category }}">
                            <div class="card-body p-1 text-white">
                                <p class="text-13 font-weight6 m-1">{{ msg }}</p>
                            </div>
                        </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block dashboard_content %}
                {% endblock %}
           </div>
        </div>

    </div>
</div>
{% endblock %}

med-app/templates/doctor/prescriptions.html
{% extends "doctor/dashboard.html"%}
{% block dashboard_content %}
     <div class="container">
        <div class="card  shadow-sm">
            <div class="card-body">
    <div class="container table-responsive pt-2 py-5">
    <table class="table table-striped table-hover text-13">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Patient</th>
            <th scope="col">Created_at</th>
          <th scope="col">Prescription Note</th>
             <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for presc in prescriptions %}
        <tr>
          <th scope="row">{% if presc.id|length==1 %}#000{{ presc.id }} {% else %}#00{{ presc.id }}{% endif %}</th>
          <td>{{ presc.patient}}</td>
            <td>{{ presc.created_at }}</td>
            <td>{{ presc.prescription}}</td>
          <td>
               <a href="{{ url_for("doctor.prescription", id=presc.id) }}" class="btn btn-sm bg-blue text-white text-13">view</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </div>
            </div>
        </div>
     </div>

{% endblock %}

med-app/templates/doctor/profile.html
{% extends "doctor/dashboard.html"%}
{% block dashboard_content %}
    <div >
        <div class="container">
            <div class="card m-1">
                <div class="card-body text-13">
                    <form method=post action="{{ url_for("doctor.save_profile") }}" role="form">
                        <h5 class="p-2">Edit Profile</h5>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Name</label>
                                    <div class=""><input type="text" class="form-control form-control-sm" name="username" value="{{ info.user }}" required></div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Email</label>
                                    <div class=""><input type="email" class="form-control form-control-sm" name="email" value="{{ info.user.email }}" required></div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Phone</label>
                                    <div class=""><input type="text" class="form-control form-control-sm" name="phone" value="{{ info.user.phone }}" required></div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Specialisation</label>
                                    <div class=""><input type="text" class="form-control form-control-sm" disabled name="spec_id" value="{{ info.spec.name }}" required></div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Address</label>
                                    <div class=""><input type="text" class="form-control form-control-sm" name="street" value="{{ info.user.location[0].street }}" required></div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group m-1">
                                    <label class="font-weight7">City</label>
                                    <div class=""><input type="text" class="form-control form-control-sm" name="city" value="{{ info.user.location[0].city }}" required></div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Country</label>
                                    <div class=""><input type="text" class="form-control form-control-sm" name="country" value="{{ info.user.location[0].country }}" required></div>
                                </div>
                            </div>
                        </div>
                        <div class="m-2">
                            <button type="submit" class="btn bg-blue text-white text-13">Save Changes</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card m-1">
                <div class="card-body text-13">
                    <form class="" role="form" method=post action="{{ url_for("doctor.change_password") }}">
                        <h5 class="">Change Password</h5>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Old Password</label>
                                    <div class=""><input type="password" class="form-control form-control-sm" name="old_password" required></div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group m-1">
                                    <label class="font-weight7">New Password</label>
                                    <div class=""><input type="password" class="form-control form-control-sm" name="new_password" required></div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Password Confirmation</label>
                                    <div class=""><input type="password" class="form-control form-control-sm" name="password_confirm" required></div>
                                </div>
                            </div>
                        </div>
                         <div class="m-2">
                            <button type="submit" class="btn bg-blue text-white text-13">Save Password</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}