med-app/models/patient.py
from extensions import db
from sqlalchemy import TIMESTAMP
from datetime import datetime
# Define models
patient_diseases = db.Table(
    'patient_diseases',
    db.Column('patient_id', db.Integer(), db.ForeignKey('patient.id')),
    db.Column('disease_id', db.Integer(), db.ForeignKey('disease.id')),
    db.Column('result', db.String(50), nullable=False),
    db.Column('create_at', TIMESTAMP, default=datetime.utcnow, nullable=False, )
)

class Patient(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    gender = db.Column(db.String(255), nullable=False)
    dob = db.Column(db.Date(), nullable=False)
    created_at = db.Column(TIMESTAMP, default=datetime.utcnow, nullable=False, )
    active = db.Column(db.Boolean())
    # user = db.relationship("User", back_populates="patient")
    prescriptions = db.relationship('Prescription', backref='patient')
    appointments = db.relationship('Appointment', backref='patient')

    def __init__(self, gender, dob, user_id, active=1):
        self.gender = gender
        self.dob = dob
        self.user_id = user_id
        self.active = active

med-app/models/prescription.py
from extensions import db
from sqlalchemy import TIMESTAMP
from datetime import datetime

class Prescription(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    prescription = db.Column(db.String(255), nullable=False)
    created_at = db.Column(TIMESTAMP, default=datetime.utcnow, nullable=False, )
    patient_id = db.Column(db.Integer, db.ForeignKey('patient.id'), nullable=False)
    doctor_id = db.Column(db.Integer, db.ForeignKey('doctor.id'), nullable=False)
    active = db.Column(db.Boolean())

    def __str__(self):
        return self.prescription

med-app/patient/routes.py
from datetime import datetime
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user
from flask_security import roles_accepted, SQLAlchemyUserDatastore
from flask_security.utils import hash_password

from extensions import db, bcrypt, SQLAlchemyError, OperationalError
from models.appointments import Appointment
from models.doctor import Doctor
from models.location import Location
from models.patient import Patient
from models.role import Role
from models.specialisation import Specialisation
from models.user import User
from models.prescription import Prescription

pat = Blueprint('patient', __name__, static_folder='../static', template_folder='../templates')


@pat.route('/')
@roles_accepted('patient')
def pat_dash():
    user = current_user.username
    return render_template('patient/dashboard_history.html', username=user)


@pat.route('/book_appointment')
@roles_accepted('patient')
def choose_doctor():
    serv = Specialisation.query.all()
    services = []
    for service in serv:
        doctors = []
        for d in service.doctors:
            doc = User.query.get(d.user_id)
            doc = {"doc": d, "user": doc}
            doctors.append(doc)
        service = {"service": service, "doctors": doctors}
        services.append(service)
    return render_template('patient/book_appointment.html', services=services)


@pat.route('/book_now/<id>', methods=['POST', 'GET'])
@roles_accepted('patient')
def book_appointment(id=None):
    if id is None:
        return "NONE"
    else:
        user = User.query.get(id)
        doctor = Doctor.query.filter_by(user_id=id).first()
        spec = Specialisation.query.get(doctor.specialisation_id)
        data = {"user": user, "doctor": doctor, "spec": spec}
        return render_template('patient/book_app_form.html', data=data)


@pat.route('/save_appointment', methods=['POST'])
def save_appointment():
    if request.method == "POST":
        patient_id = current_user.id
        patient = Patient.query.filter_by(user_id=patient_id).first()
        doctor_id = request.form.get("doctor_id")
        status = "pending"
        time = request.form.get('time')
        date = request.form.get('date')
        comment = request.form.get('comment')
        appointment = Appointment(patient_id=patient.id, doctor_id=doctor_id, status=status, time=time, date=date,
                                  comment=comment)
        db.session.add(appointment)
        db.session.commit()
        flash(f"You have successful scheduled an appointment on with a doctor on {date} {time}", "success text-center")
        return redirect(url_for("patient.appointments_history"))


@pat.route('/appointment-cancel/<id>', methods=['POST', 'GET'])
@roles_accepted('patient')
def cancel_appointment(id=None):
    if id is None:
        return "NONE"
    else:
        app_cancelled = Appointment.query.filter_by(id=id).update({"status": "cancel"})
        db.session.commit()
        flash(f"Appointment successfully cancelled", "success text-center")
        return redirect(url_for("patient.appointments_history"))


@pat.route('/appointments-history')
@roles_accepted('patient')
def appointments_history():
    patient = Patient.query.filter_by(user_id=current_user.id).first()
    # appointments = Appointment.query.filter(Appointment.patient_id==patient.id).all()
    appointments = []
    for appointment in patient.appointments:
        doc = Doctor.query.get(appointment.doctor_id)
        user = User.query.get(doc.user_id)
        service = Specialisation.query.get(doc.specialisation_id)
        new_app = {"consultation_fee": doc.consultation_fee, "doctor": user, "service": service,
                   "date": appointment.date, "time": appointment.time, "status": appointment.status,
                   "id": appointment.id, "created_at": appointment.created_at}
        appointments.append(new_app)
    return render_template('patient/appointments_history.html', appointments=appointments)


user_datastore = SQLAlchemyUserDatastore(db, User, Role)


@pat.route('/add_patient', methods=['GET', 'POST'])
def add_patient():
    if request.method == "POST":
        username = request.form.get('username')
        email = request.form.get('email')
        password = request.form.get('password')
        password_confirm = request.form.get('password_confirm')
        if password.__ne__(password_confirm):
            flash("Password does not match Password confirmation. Please match the passwords.", "alert")
            return render_template("security/register_user.html")
        # LOCATION
        street = request.form.get('street')
        city = request.form.get('city')
        country = request.form.get('country')

        # PATIENT
        dob = request.form.get('dob')
        sex = request.form.get('sex')
        patient_role = Role(name='patient')

        try:
            user = user_datastore.create_user(username=username, email=email,
                                              password=bcrypt.generate_password_hash(password), roles=[patient_role])
            db.session.add(user)
            db.session.commit()
            location = Location(street=street, city=city, country=country, user_id=user.id)
            patient1 = Patient(dob=dob, gender=sex, user_id=user.id)
            db.session.add(location)
            db.session.add(patient1)
        except SQLAlchemyError as e:
            flash(f"{str(e.__dict__['orig'])}", "danger text-center")
            db.session.rollback()
            return render_template("security/register_user.html")
        except OperationalError as o:
            flash(f"{str(o.__dict__['orig'])}", "danger text-center")
            db.session.rollback()
            return render_template("security/register_user.html")
        else:
            db.session.commit()
        return redirect(url_for("main.login"))


@pat.route('/profile', methods=['GET'])
@roles_accepted('patient')
def edit_profile():
    user_info = current_user
    pat = Patient.query.filter_by(user_id=current_user.id).first()
    specs = Specialisation.query.all()
    data = {"user": user_info, "pat": pat}
    return render_template('patient/profile.html', info=data)


@pat.route('/save-profile', methods=['POST', 'GET'])
@roles_accepted('patient')
def save_profile():
    username = request.form.get('username')
    email = request.form.get('email')
    phone = request.form.get('phone')
    dob = request.form.get('dob')
    sex = request.form.get('gender')
    street = request.form.get('street')
    city = request.form.get('city')
    country = request.form.get('country')
    try:
        user = User.query.filter_by(id=current_user.id).update({"username": username, "email": email, "phone": phone})
        location = Location.query.filter_by(user_id=current_user.id).update({"street": street, "city": city, "country": country})
    except SQLAlchemyError as e:
        flash(f"{str(e.__dict__['orig'])}", "alert text-center")
        db.session.rollback()
        redirect(url_for("patient.edit_profile"))
    except OperationalError as o:
        flash(f"{str(o.__dict__['orig'])}", "alert text-center")
        db.session.rollback()
        return redirect(url_for("patient.edit_profile"))
    else:
        db.session.commit()
    flash("Successfully edit user profile.", "success text-center")
    return redirect(url_for("patient.edit_profile"))


@pat.route('/change-password', methods=['POST', 'GET'])
@roles_accepted('patient')
def change_password():
    old_pwd = request.form.get('old_password')
    new_pwd = request.form.get('new_password')
    confirm_pwd = request.form.get('password_confirm')
    user = User.query.filter_by(id=current_user.id).first()
    if user and user.verify_password(old_pwd):
        if new_pwd.__ne__(confirm_pwd):
            flash("Password does not match Password confirmation. Please match the passwords.", "alert")
            return redirect(url_for("patient.edit_profile"))
        user = User.query.filter_by(id=current_user.id).update({"password": bcrypt.generate_password_hash(new_pwd)})
        db.session.commit()
        flash("Successfully change password!", "success text-center")
        return redirect(url_for("patient.edit_profile"))


@pat.route('/prescriptions', methods=['GET'])
@roles_accepted('patient')
def prescriptions():
    prescriptions = Patient.query.filter_by(user_id=current_user.id).first().prescriptions
    prescrips = []
    for p in prescriptions:
        p_user = User.query.get(Doctor.query.get(p.doctor_id).user_id)
        presc = {"id": str(p.id), "doctor": p_user, "created_at": p.created_at, "prescription": p.prescription}
        prescrips.append(presc)
    return render_template("patient/prescriptions.html", prescriptions=prescrips)

@pat.route('/prescription/<id>', methods=['GET'])
@roles_accepted('patient')
def prescription(id):
    prescription = Prescription.query.get(id)
    return render_template("patient/prescription.html", presc=prescription)
"""

def change_password():
    return "password changed"



def delete_appointment_record():
    return "deleting record"

def diagnosis_history():
    return "appointment history"

def clear_diagnosis_history():
    return "appointment history"

def remove_diagnosis_record():
    return "appointment history"


"""

med-app/templates/patient/appointments_history.html
{% extends "patient/dashboard.html" %}
{% block dashboard_content %}
     <div class="container">
        <div class="card  shadow-sm">
            <div class="card-body">
    <div class="container table-responsive pt-1 py-5">
    <table class="table table-striped table-hover text-13">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Service</th>
          <th scope="col">Doctor</th>
             <th scope="col">Consultation Fee</th>
          <th scope="col">Appointment Date</th>
            <th scope="col">Created At</th>
             <th scope="col">Status</th>
             <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for appointment in appointments %}
        <tr>
          <th scope="row">#001</th>
          <td>{{ appointment.service }}</td>
          <td>{{ appointment.doctor}}</td>
          <td>{{appointment.consultation_fee}}</td>
            <td>{{ appointment.date }} {{ appointment.time }}</td>
            <td>{{ appointment.created_at }}</td>
          <td>
               {% if appointment.status=="cancel" %}
              <span class="badge bg-danger">Cancelled</span>
                    {% elif appointment.status=="approved" %}
              <span class="badge bg-success">Approved</span>
                {% elif appointment.status=="pending" %}
              <span class="badge bg-orange">Pending</span>
              {% else %}
                    <span class="badge bg-primary">{{ appointment.status }}</span>
              {% endif %}
          </td>
          <td>
              {% if appointment.status=="cancel" %}
               <button disabled class="btn btn-sm btn-danger">cancelled</button>
              {% elif appointment.status=="pending" %}
              <a class="btn btn-sm btn-danger"
                 href="{{url_for('patient.cancel_appointment', id=appointment.id) }}">Cancel</a>
              {% else %}
              <button disabled class="btn btn-sm btn-success">DONE</button>
              {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </div>
            </div>
        </div>
     </div>
{% endblock %}

med-app/templates/patient/book_app_form.html
{% extends "patient/dashboard.html" %}
{% block dashboard_content %}
    <div class="container">
        <div class="card">
            <div class="card-body ">
                <div class="d-flex justify-content-center">

                <div class="col-md-5 p-2">
                    <h4 class="text-center font-weight7 text-15">BOOK APPOINTMENT</h4>
                    <form action="{{ url_for("patient.save_appointment") }}" method=post role="form" style="width: 400px">
                        <div class="form-group m-2">
                            <label class="text-13 font-weight6">Service</label>
                            <input type="text"id="service"class="form-control rounded-0" disabled value="{{ data.spec }}" required>

                        </div>
                        <div class="form-group  m-2">
                            <label class="text-13 font-weight6">Doctor</label>
                            <input type="text"id="doctor"class="form-control rounded-0" disabled value="{{ data.user.username }}" required>
                            <div><input name="doctor_id" class="d-none" value="{{ data.doctor.id }}"></div>
                        </div>
                        <div class="form-group  m-2">
                            <label class="text-13 font-weight6">Consultation Fee</label>
                            <input type="text" name="fee"class="form-control rounded-0" disabled value="${{ data.doctor.consultation_fee }}" required>
                        </div>
                        <div class="form-group  m-2">
                            <label class="text-13 font-weight6">Appointment Date</label>
                            <input type="date" name="date"class="form-control rounded-0" required>
                        </div>
                        <div class="form-group  m-2">
                            <label class="text-13 font-weight6">Appointment Time</label>
                            <input type="time" name="time"class="form-control rounded-0" required>
                        </div>
                        <div class="form-group  m-2">
                            <label class="text-13 font-weight6">Symptoms</label>
                            <textarea class="form-control rounded-0" name="comment" required></textarea>
                        </div>
                        <div>
                            <button class="btn w-100 rounded-0 bg-blue font-weight6 text-white text-center">Submit</button>
                        </div>


                    </form>
                </div>
                   <!-- <div class="col-md-7 p-2">
                        <div class="pt-4">
                            <h4 class="pl-3 p-2 m-0 ml-2">RECENT APPOINTMENTS</h4>

                            <div class="container table-responsive pl-2 pt-2 py-5">
                                <table class="table table-striped table-hover text-13 font-weight4">
                                    <thead class="thead-dark">
                                        <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">Service</th>
                                            <th scope="col">Doctor</th>
                                            <th scope="col">Date and Time</th>
                                            <th scope="col">Status</th>
                                        </tr>
                                      </thead>
                                    <tbody>
                                        <tr>
                                            <th scope="row">1</th>
                                            <td>{{ Oncology }}</td>
                                            <td>Marting Garris</td>
                                            <td>21 Oct 10.00a.m</td>
                                            <td>Pending</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>-->
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

med-app/templates/patient/book_appointment.html
{% extends "patient/dashboard.html" %}
{% block dashboard_content %}
    <div class="container book-appointment">
        <div class="d-flex justify-content-center">
            <div class="col-md-10">
                <div class="row">
                    {% for data in services %}
                        {% if data.doctors | length > 0 %}
                        <div class="col-md-3 p-1 col-lg-3">
                            <div class="card img-card p-1">
                               <div class="card-body p-1">
                                    <div class="caption text-center">
                                        <p class="m-1 font-weight8 text-14">{{ data.service }}</p>
                                    </div>
                                   <div class="d-flex justify-content-center tex-center">
                                       <div class="image ">
                                            <img src="{{ url_for('static',filename='uploads/'+data.service.image)}}">
                                        </div>
                                   </div>

                                    <div>
                                        <h6 class="font-weight6 p-3 pt-1 pb-1 text-13 text-center">Choose Doctor ...</h6>
                                        {% if data.doctors != [] %}
                                            <ul style="height: 100px; overflow-y: scroll"
                                                class="list-group text-13 font-weight5  border-0 rounded-0 remove-bl-br">
                                                    {% for doctor in data.doctors %}
                                                    <li class="list-group-item doc-list-item" >

                                                        <a href="{{url_for('patient.book_appointment', id=doctor.user.id) }}"
                                                           class="text-dark doc-link">{{ doctor.user.username }}</a> </li>
                                                    {% endfor %}
                                            </ul>
                                        {% endif %}
                                    </div>

                               </div>
                            </div>
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>

        </div>
    </div>
{% endblock %}

med-app/templates/patient/dashboard.html
{% extends "base.html" %}
{% block body %}
    <div class="main-wrap">
    <input id="slide-sidebar" type="checkbox" role="button" />
        <label for="slide-sidebar" class="toggle-label"><span class="fa-stack fa-md "><i class="fa fa-th-list fa-stack-1x "></i></span></label>
    <div class="sidebar position-fixed">
        <div class="container p-1 pb-2 pt-3">
            <h4 class="text-center heading text-orange font-weight9">
                <span class="fa-stack fa-md"><i class="fa fa-dashboard fa-stack-1x "></i></span>
                <span class="text-15">DASHBOARD</span>
            </h4>
        </div>
        <div class="container">
            <ul class="list-group list-unstyled text-13">
            <li class="list-group-item"><a class="navbar-link text-black" href="/patient/book_appointment">
                 <span class="fa-stack fa-md "><i class="fa fa-book fa-stack-1x "></i></span>Book Appointment</a></li>
            <li class="list-group-item"><a class="navbar-link text-black" href="/patient/appointments-history">
                 <span class="fa-stack fa-md "><i class="fa fa-history fa-stack-1x "></i></span>Appointments History</a></li>
            <li class="list-group-item"><a class="navbar-link text-black" href="/dashboard">
                 <span class="fa-stack fa-md "><i class="fa fa-ambulance fa-stack-1x " ></i></span>Diseases Diagnosis</a></li>
            <li class="list-group-item"><a class="navbar-link text-black" href="/patient/prescriptions">
                <span class="fa-stack fa-md "><i class="fa fa-plus-circle fa-stack-1x "></i></span> Prescriptions</a></li>
            <li class="list-group-item"><a class="navbar-link text-black" href="/patient/profile">
                 <span class="fa-stack fa-md "><i class="fa fa-wrench fa-stack-1x "></i></span>My Profile</a>
            </li>
                <li class="list-group-item">
               <a href="#"  class="navbar-link text-black">
                   <span class="fa-stack fa-md"><i class="fa fa-server fa-stack-1x "></i></span>Contact</a>
            </li>
        </ul>
        </div>
    </div>
    <div class="portfolio">
        <nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand text-orange font-weight9" href="#">HD & M</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse  " id="navbarNav">
                    <ul class="navbar-nav ms-auto font-weight6 text-14">
                        <li class="nav-item m-2 mr-3">
                          <a class="nav-link text-black" aria-current="page" href="#">
                          <i class="fa fa-home p-1 pr-2 text-15"></i>Home</a>
                        </li>
                        <li class="nav-item m-2 mr-3">
                          <a class="nav-link  pr-2 text-black" href="#"><i class="fa fa-info-circle p-1 pr-2 text-14"></i>About</a>
                        </li>
                        <li class="nav-item m-2 mr-3">
                            <a class="nav-link text-black" href="{{ url_for('admin.logout_') }}">
                                <i class="fa fa-sign-out p-1 pr-2 text-14"></i>Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="dashboard container">
           <div class="pt-1">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category,msg in messages %}
                        <div class="card bg-{{ category }}">
                            <div class="card-body p-1 text-white">
                                <p class="text-13 font-weight6 m-1">{{ msg }}</p>
                            </div>
                        </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block dashboard_content %}
                {% endblock %}
           </div>
        </div>

    </div>
</div>
{% endblock %}

med-app/templates/patient/prescriptions.html
{% extends "patient/dashboard.html"%}
{% block dashboard_content %}
     <div class="container">
        <div class="card  shadow-sm">
            <div class="card-body">
    <div class="container table-responsive pt-1 py-5">
    <table class="table table-striped table-hover text-13">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Doctor</th>
            <th scope="col">Created_at</th>
          <th scope="col">Prescription Note</th>
             <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for presc in prescriptions %}
        <tr>
          <th scope="row">{% if presc.id|length==1 %}#000{{ presc.id }} {% else %}#00{{ presc.id }}{% endif %}</th>
          <td>{{ presc.doctor}}</td>
            <td>{{ presc.created_at }}</td>
            <td>{{ presc.prescription}}</td>
          <td>
               <a href="{{ url_for("patient.prescription", id=presc.id) }}" class="btn btn-sm bg-blue text-white text-13">view</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </div>
            </div>
        </div>
     </div>

{% endblock %}

med-app/templates/patient/profile.html
{% extends "patient/dashboard.html"%}
{% block dashboard_content %}
    <div >
        <div class="container">
            <div class="card m-1">
                <div class="card-body text-13">
                    <form method=post action="{{ url_for("patient.save_profile") }}" role="form">
                        <h5 class="p-2">Edit Profile</h5>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Name</label>
                                    <div class=""><input type="text" class="form-control form-control-sm" name="username" value="{{ info.user }}" required></div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Email</label>
                                    <div class=""><input type="email" class="form-control form-control-sm" name="email" value="{{ info.user.email }}" required></div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Phone</label>
                                    <div class=""><input type="text" class="form-control form-control-sm" name="phone" value="{{ info.user.phone }}" required></div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Date of Birth</label>
                                    <div class=""><input type="date" class="form-control form-control-sm" name="date" value="{{ info.pat.dob }}" required></div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Address</label>
                                    <div class=""><input type="text" class="form-control form-control-sm" name="street" value="{{ info.user.location[0].street }}" required></div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group m-1">
                                    <label class="font-weight7">City</label>
                                    <div class=""><input type="text" class="form-control form-control-sm" name="city" value="{{ info.user.location[0].city }}" required></div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Country</label>
                                    <div class=""><input type="text" class="form-control form-control-sm" name="country" value="{{ info.user.location[0].country }}" required></div>
                                </div>
                            </div>
                        </div>
                        <div class="m-2">
                            <button type="submit" class="btn bg-blue text-white text-13">Save Changes</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card m-1">
                <div class="card-body text-13">
                    <form class="" role="form" method=post action="{{ url_for("patient.change_password") }}">
                        <h5 class="">Change Password</h5>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Old Password</label>
                                    <div class=""><input type="password" class="form-control form-control-sm" name="old_password" required></div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group m-1">
                                    <label class="font-weight7">New Password</label>
                                    <div class=""><input type="password" class="form-control form-control-sm" name="new_password" required></div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group m-1">
                                    <label class="font-weight7">Password Confirmation</label>
                                    <div class=""><input type="password" class="form-control form-control-sm" name="password_confirm" required></div>
                                </div>
                            </div>
                        </div>
                         <div class="m-2">
                            <button type="submit" class="btn bg-blue text-white text-13">Save Password</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}