med-app/main/routes.py
import joblib
import numpy as np
import pandas as pd
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required, login_user
from flask_security import logout_user
from werkzeug.security import check_password_hash
from models.user import User
from extensions import db, login_manager, bcrypt
import pickle
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import warnings

# warnings.filterwarnings("ignore")

filename = 'diabetes-prediction-rfc-model.pkl'
classifier = pickle.load(open(filename, 'rb'))
model = pickle.load(open('model.pkl', 'rb'))
model1 = pickle.load(open('model1.pkl', 'rb'))
main = Blueprint('main', __name__, static_folder='../static', template_folder='../templates')


def get_user(user_id):
    user = User.query.filter_by(id=user_id).first()
    return user


@login_manager.user_loader
def load_user(user_id):
    return get_user(user_id)


@main.route('/login')
def login():
    return render_template('security/login_user.html')


@main.route('/sign-in', methods=['POST', 'GET'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    # remember_me = True if request.form.get('remember') else False
    user = User.query.filter_by(email=email).first()
    if user and user.verify_password(password) and user.active==1:
        login_user(user)
        flash(f"Hi {user.username}!", "success")
        if user.roles[0].name.__eq__("patient"):
            return redirect(url_for('patient.pat_dash'))
        if user.roles[0].name.__eq__("admin"):
            return redirect(url_for('admin.admin_dash'))
        if user.roles[0].name.__eq__("doctor"):
            return redirect(url_for('doctor.doc_dash'))
        else:
            flash("Error! Recreate your account, please")
            return "NO DEFINED ROLE"

    flash("Invalid Password/ Email. Please Try Again!")
    return render_template("security/login_user.html")


@main.route("/")
def index():
    return render_template("index.html")


@main.route('/about')
def about():
    return render_template("about.html")


@main.route('/help')
def help():
    return render_template("help.html")


@main.route('/terms')
def terms():
    return render_template("tc.html")


@main.route("/home")
@login_required
def home():
    return f"{current_user.username}. Your email is {current_user.email}"


@main.errorhandler(404)
def page_not_found(e):
    # note that we set the 404 status explicitly
    return render_template('404.html'), 404


@main.errorhandler(500)
def internal_server_error(e):
    # note that we set the 500 status explicitly
    return render_template('500.html'), 500


@main.route("/add_phone_number")
@login_required
def add_phone():
    return render_template("/security/add_phone.html")


@main.route("/update_phone", methods=["GET", "POST"])
@login_required
def update_phone():
    if request.method == "POST":
        phone_number = request.form["phone_number"]
        # user = User.query.filter_by(email=current_user.email).first()
        user_updated = User.query.filter_by(id=current_user.id).update(dict(phone=phone_number))
        db.session.commit()
    return redirect("/home")


@main.route("/dashboard")
@login_required
def dashboard():
    return render_template("diseases/dashboard.html")


@main.route("/disindex")
def disindex():
    return render_template("diseases/disindex.html")


@main.route("/cancer")
@login_required
def cancer():
    return render_template("diseases/cancer.html")


@main.route("/diabetes")
@login_required
def diabetes():
    return render_template("diseases/diabetes.html")


@main.route("/heart")
@login_required
def heart():
    return render_template("diseases/heart.html")


@main.route("/kidney")
@login_required
def kidney():
    return render_template("diseases/kidney.html")


def ValuePredictor(to_predict_list, size):
    to_predict = np.array(to_predict_list).reshape(1, size)
    if size == 7:
        loaded_model = joblib.load('kidney_model.pkl')
        result = loaded_model.predict(to_predict)
    return result[0]


@main.route("/predictkidney", methods=['GET', 'POST'])
def predictkidney():
    if request.method == "POST":
        to_predict_list = request.form.to_dict()
        to_predict_list = list(to_predict_list.values())
        to_predict_list = list(map(float, to_predict_list))
        if len(to_predict_list) == 7:
            result = ValuePredictor(to_predict_list, 7)
    if (int(result) == 1):
        prediction = "Patient has a high risk of Kidney Disease, please consult your doctor immediately"
    else:
        prediction = "Patient has a low risk of Kidney Disease"
    return render_template("diseases/kidney_result.html", prediction_text=prediction)


@main.route("/liver")
@login_required
def liver():
    return render_template("diseases/liver.html")


def ValuePred(to_predict_list, size):
    to_predict = np.array(to_predict_list).reshape(1, size)
    if (size == 7):
        loaded_model = joblib.load('liver_model.pkl')
        result = loaded_model.predict(to_predict)
    return result[0]


@main.route('/predictliver', methods=["POST"])
def predictliver():
    if request.method == "POST":
        to_predict_list = request.form.to_dict()
        to_predict_list = list(to_predict_list.values())
        to_predict_list = list(map(float, to_predict_list))
        if len(to_predict_list) == 7:
            result = ValuePred(to_predict_list, 7)

    if int(result) == 1:
        prediction = "Patient has a high risk of Liver Disease, please consult your doctor immediately"
    else:
        prediction = "Patient has a low risk of Kidney Disease"
    return render_template("diseases/liver_result.html", prediction_text=prediction)


@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for(''))


@main.route('/predict', methods=['POST'])
def predict():
    input_features = [int(x) for x in request.form.values()]
    features_value = [np.array(input_features)]
    features_name = ['clump_thickness', 'uniform_cell_size', 'uniform_cell_shape', 'marginal_adhesion',
                     'single_epithelial_size', 'bare_nuclei', 'bland_chromatin', 'normal_nucleoli', 'mitoses']
    df = pd.DataFrame(features_value, columns=features_name)
    output = model.predict(df)
    if output == 4:
        res_val = "a high risk of Breast Cancer"
    else:
        res_val = "a low risk of Breast Cancer"

    return render_template('diseases/cancer_result.html', prediction_text=f'Patient has {res_val}')


##################################################################################

df1 = pd.read_csv('diabetes.csv')

# Renaming DiabetesPedigreeFunction as DPF
df1 = df1.rename(columns={'DiabetesPedigreeFunction': 'DPF'})

# Replacing the 0 values from ['Glucose','BloodPressure','SkinThickness','Insulin','BMI'] by NaN
df_copy = df1.copy(deep=True)
df_copy[['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']] = df_copy[['Glucose', 'BloodPressure',
                                                                                    'SkinThickness', 'Insulin',
                                                                                    'BMI']].replace(0, np.NaN)

# Replacing NaN value by mean, median depending upon distribution
df_copy['Glucose'].fillna(df_copy['Glucose'].mean(), inplace=True)
df_copy['BloodPressure'].fillna(df_copy['BloodPressure'].mean(), inplace=True)
df_copy['SkinThickness'].fillna(df_copy['SkinThickness'].median(), inplace=True)
df_copy['Insulin'].fillna(df_copy['Insulin'].median(), inplace=True)
df_copy['BMI'].fillna(df_copy['BMI'].median(), inplace=True)

# Model Building

X = df1.drop(columns='Outcome')
y = df1['Outcome']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

# Creating Random Forest Model

classifier = RandomForestClassifier(n_estimators=20)
classifier.fit(X_train, y_train)

# Creating a pickle file for the classifier
filename = 'diabetes-prediction-rfc-model.pkl'
pickle.dump(classifier, open(filename, 'wb'))


#####################################################################


@main.route('/predictt', methods=['POST'])
def predictt():
    if request.method == 'POST':
        preg = request.form['pregnancies']
        glucose = request.form['glucose']
        bp = request.form['bloodpressure']
        st = request.form['skinthickness']
        insulin = request.form['insulin']
        bmi = request.form['bmi']
        dpf = request.form['dpf']
        age = request.form['age']

        data = np.array([[preg, glucose, bp, st, insulin, bmi, dpf, age]])
        my_prediction = classifier.predict(data)

        return render_template('diseases/diab_result.html', prediction=my_prediction)


############################################################################################################

@main.route('/predictheart', methods=['POST'])
def predictheart():
    input_features = [float(x) for x in request.form.values()]
    features_value = [np.array(input_features)]

    features_name = ["age", "trestbps", "chol", "thalach", "oldpeak", "sex_0",
                     "  sex_1", "cp_0", "cp_1", "cp_2", "cp_3", "  fbs_0",
                     "restecg_0", "restecg_1", "restecg_2", "exang_0", "exang_1",
                     "slope_0", "slope_1", "slope_2", "ca_0", "ca_1", "ca_2", "thal_1",
                     "thal_2", "thal_3"]

    df = pd.DataFrame(features_value, columns=features_name)
    output = model1.predict(df)

    if output == 1:
        res_val = "a high risk of Heart Disease"
    else:
        res_val = "a low risk of Heart Disease"

    return render_template('diseases/heart_result.html', prediction_text='Patient has {}'.format(res_val))

med-app/templates/diseases/cancer.html
{% extends "diseases/main.html" %}
{% block disease_body %}
    <div class="p-4" style="background: #F2F2F2">

    <div class="p-3" >
        <h4 class="font-weight8 text-center">Breast Cancer Prediction</h4>
        <h5 class="font-weight6 text-center">Please enter the patient details</h5>
    </div>
    <div class="d-flex justify-content-center">
        <div class="card"  style="width: 500px;">
            <div class="card-body">
            <form action="{{ url_for('main.predict')}}" style="width: 470px;" method="post" class="text-14 form-inline" style="width: 400px;">
                <div class="tabcontent" id="new">
                     <div class="input-group d-flex justify-content-between m-2">
                        <label for="clump_thickness" class="font-weight6">Clump Thickness </label>
                         <div><input type="number" class="form-control" name="clump_thickness" required="required"></div>
                     </div>
                      <div class="input-group d-flex justify-content-between m-2">
                        <label for="uniform_cell_size" class="font-weight6">Uniform Cell size</label>
                          <div><input type="number" class="form-control" name="uniform_cell_size" required="required"></div>
                      </div>
                      <div class="input-group d-flex justify-content-between m-2">
                        <label for="uniform_cell_shape" class="font-weight6">Uniform Cell shape</label>
                        <div><input type="number" class="form-control" name="uniform_cell_shape" required="required" /></div>
                      </div>
                      <div class="input-group d-flex justify-content-between m-2">
                        <label for="marginal_adhesion " class="font-weight6">Marginal Adhesion</label>
                        <div><input type="number" class="form-control" name="marginal_adhesion" required="required" /></div>
                      </div>
                      <div class="input-group d-flex justify-content-between m-2">
                        <label for="single_epithelial_size" class="font-weight6">Single Epithelial Cell Size</label>
                        <div><input type="number" class="form-control" name="single_epithelial_size" required="required" /></div>
                      </div>
                      <div class="input-group d-flex justify-content-between m-2">
                        <label for="bare_nuclei" class="font-weight6">Bare Nuclei</label>
                        <div><input type="number" class="form-control" name="bare_nuclei" required="required" /></div>
                      </div>
                      <div class="input-group d-flex justify-content-between m-2">
                        <label for="bland_chromatin" class="font-weight6">Bland Chromatin</label>
                        <div><input type="number" class="form-control" name="bland_chromatin" required="required" /></div>
                      </div>
                      <div class="input-group d-flex justify-content-between m-2">
                        <label for="normal_nucleoli" class="font-weight6">Normal Nucleoli</label>
                        <div><input type="number" class="form-control" name="normal_nucleoli" required="required" /></div>
                      </div>
                      <div class="input-group d-flex justify-content-between m-2">
                        <label for="mitoses" class="font-weight6">Mitoses</label>
                        <div><input type="number" class="form-control" name="mitoses" required="required" /></div>
                      </div>
                      <div class="m-2">
                          <button type="submit" class="btn bg-blue text-white text-14 w-100 text-center">Predict</button>
                      </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

med-app/templates/diseases/cancer_result.html
{% extends "base.html" %}
    {% block body %}
    <div id="assess" style=" padding-top: 3rem;
    padding-bottom: 3rem;
    color: #5a5a5a;
    font-family: 'Poppins', sans-serif;
    overflow-x: hidden;">
        <div style="max-width: 700px;" class=" px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center container">
            <h1 class="display-6">Diseases Diagnosis</h1>
            <p class="lead">Please find below the Disease Diagnosis Results</p>
        </div>
        <div class="container themed-container " style="
        padding: 15px;
        margin-bottom: 30px;
        background-color: rgba(0, 123, 255, .15);
        border: 1px solid rgba(0, 123, 255, .2);
    "><h1 style="text-align: center;">{{prediction_text}}</h1></div>
        <p style="text-align: center;">Click <a href="/disindex">here</a> to learn more about Breast Cancer</p>
        <p style="text-align: center;">&copy;diseases.diagnosis.com</p>
    </div>
    <br/>
{% endblock %}

med-app/templates/diseases/diabetes.html
{% extends "diseases/main.html" %}
{% block disease_body %}
    <div class="p-4" style="background: #F2F2F2">
        <div class="p-3" >
            <h4 class="font-weight8 text-center">Diabetes Prediction</h4>
            <h5 class="font-weight6 text-center">Please enter the patient details</h5>
        </div>
        <div class="d-flex justify-content-center">
            <div class="card"  style="width: 500px;">
                <div class="card-body">

    <form action="{{ url_for('main.predictt')}}"  style="width: 470px;" method="post" class="text-14 form-inline">
            <div class="tabcontent" id="new">
                 <div class="input-group d-flex justify-content-between m-2">
                    <label for="pregnancies" class="font-weight6">Number of Pregnancies</label>
                     <div><input class="form-control" type="number" name="pregnancies" placeholder="eg. 0 for male" required="required"/></div>
                 </div>
                  <div class="input-group d-flex justify-content-between m-2">
                    <label for="glucose" class="font-weight6">Glucose Level (mg/dL)</label>
                      <div><input class="form-control" type="number" name="glucose" placeholder="eg. 80" required="required"/></div>
                  </div>
                  <div class="input-group d-flex justify-content-between m-2">
                    <label for="bloodpressure" class="font-weight6">Blood Pressure (mmHg)</label>
                      <div><input class="form-control" type="number" name="bloodpressure" placeholder="eg. 80" required="required"/></div>
                  </div>
                  <div class="input-group d-flex justify-content-between m-2">
                    <label for="skinthickness" class="font-weight6">Skin Thickness (mm)</label>
                      <div><input class="form-control" type="number" name="skinthickness" placeholder="eg. 20" required="required"/></div>
                  </div>
                  <div class="input-group d-flex justify-content-between m-2">
                    <label for="insulin" class="font-weight6">Insulin Level (IU/mL) </label>
                      <div><input class="form-control" type="number" name="insulin" placeholder="eg. 80" required="required"/></div>
                  </div>
                  <div class="input-group d-flex justify-content-between m-2">
                    <label for="bmi" class="font-weight6">Body Mass Index (kg/m²)</label>
                      <div><input class="form-control" type="number" name="bmi" placeholder="eg. 23.1" required="required"/></div>
                  </div>
                  <div class="input-group d-flex justify-content-between m-2">
                    <label for="dpf" class="font-weight6">Diabetes Pedigree Function</label>
                      <div><input class="form-control" type="text" name="dpf" placeholder="eg. 0.52" required="required"/></div>
                  </div>
                  <div class="input-group d-flex justify-content-between m-2">
                    <label for="age" class="font-weight6">Patient Age in Years</label>
                      <div><input class="form-control" type="number" name="age" placeholder="eg. 34" required="required"/></div>
                  </div>
                <div class="m-2">
                    <button type="submit" class="btn bg-blue text-white text-14 w-100 text-center">Predict</button>
                </div></div>
    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

med-app/templates/diseases/heart.html
{% extends "diseases/main.html" %}
{% block disease_body %}
    <div class="p-4" style="background: #F2F2F2">
        <div class="p-3" >
            <h4 class="font-weight8 text-center">Heart Disease Prediction</h4>
            <h5 class="font-weight6 text-center">Please enter the patient details</h5>
        </div>
        <div class="d-flex justify-content-center">
            <div class="card"  style="width: 500px;">
                <div class="card-body">
                    <form action="{{ url_for('main.predictheart')}}"  style="width: 470px;" method="post" class="text-14 form-inline">
                    <div class="tabcontent" id="new">
                         <div class="input-group d-flex justify-content-between m-2">
                            <label for="age" class="font-weight6">Age in Years</label>
                             <div><input class="form-control" type="number" name="age" placeholder="eg. 34" required="required"/></div>
                         </div>
                         <div class="input-group d-flex justify-content-between m-2">
                            <label for="trestbps" class="font-weight6">Trest Bps</label>
                             <div><input class="form-control" type="number" name="trestbps" placeholder="trestbps" required="required"/></div>
                         </div>
                         <div class="input-group d-flex justify-content-between m-2">
                            <label for="chol" class="font-weight6">Cholesterol</label>
                             <div><input class="form-control" type="number" name="chol" placeholder="chol" required="required"/></div></div>
                        <div class="input-group d-flex justify-content-between m-2">
                            <label for="thalach" class="font-weight6">Thalach</label>
                            <div><input class="form-control" type="number" name="thalach" placeholder="thalach" required="required"/></div>
                        </div>
                        <div class="input-group d-flex justify-content-between m-2">
                            <label for="oldpeak" class="font-weight6">Old Peak</label>
                            <div><input class="form-control" type="number" name="oldpeak" placeholder="oldpeak" required="required"/></div>
                        </div>
                        <div class="input-group d-flex justify-content-between m-2">
                            <label for="sex_0" class="font-weight6">Sex_0</label>
                            <div><input class="form-control" type="number" name="sex_0" placeholder="sex_0" required="required"/></div>
                        </div>
                       <div class="input-group d-flex justify-content-between m-2">
                            <label for="sex_1" class="font-weight6">Sex_1</label>
                           <div><input class="form-control" type="number" name="sex_1" placeholder="sex_1" required="required"/></div>
                      </div>
                   <div class="input-group d-flex justify-content-between m-2">
                        <label for="CP_0" class="font-weight6">CP_0</label>
                       <div><input class="form-control" type="number" name="CP_0" placeholder="CP_0" required="required"/></div>
                   </div>
                   <div class="input-group d-flex justify-content-between m-2">
                    <label for="CP_1" class="font-weight6">CP_1</label>
                       <div><input class="form-control" type="number" name="CP_1" placeholder="CP_1" required="required"/></div>
                  </div>
                   <div class="input-group d-flex justify-content-between m-2">
                        <label for="CP_2" class="font-weight6">CP_2</label>
                       <div><input class="form-control" type="number" name="CP_2" placeholder="CP_2" required="required"/></div>
                  </div>
                   <div class="input-group d-flex justify-content-between m-2">
                        <label for="CP_3" class="font-weight6">CP_3</label>
                       <div><input class="form-control" type="number" name="CP_3" placeholder="CP_3" required="required"/></div>
                   </div>
                   <div class="input-group d-flex justify-content-between m-2">
                        <label for="fbs_0" class="font-weight6">FBS_0</label>
                       <div><input class="form-control" type="number" name="FBS_0" placeholder="FBS_0" required="required"/></div>
                  </div>
                   <div class="input-group d-flex justify-content-between m-2">
                        <label for="restecg_0" class="font-weight6">RESTECG_0</label>
                       <div><input class="form-control" type="number" name="restecg_0" placeholder="restecg_0" required="required"/></div>
                  </div>
                   <div class="input-group d-flex justify-content-between m-2">
                        <label for="restecg_1" class="font-weight6">RESTECG_1</label>
                       <div><input class="form-control" type="number" name="restecg_1" placeholder="restecg_1" required="required"/></div>
                  </div>
                   <div class="input-group d-flex justify-content-between m-2">
                        <label for="restecg_2" class="font-weight6">RESTECG_2</label>
                       <div><input class="form-control" type="number" name="restecg_2" placeholder="restecg_2" required="required"/></div>
                  </div>
                   <div class="input-group d-flex justify-content-between m-2">
                        <label for="exang_0" class="font-weight6">EXANG_0</label>
                       <div><input class="form-control" type="number" name="EXANG_0" placeholder="EXANG_0" required="required"/></div>
                  </div>
                   <div class="input-group d-flex justify-content-between m-2">
                        <label for="exang_1" class="font-weight6">EXANG_1</label>
                       <div><input class="form-control" type="number" name="EXANG_1" placeholder="EXANG_1" required="required"/></div>
                  </div>
                   <div class="input-group d-flex justify-content-between m-2">
                        <label for="slope_0" class="font-weight6">SLOPE_0</label>
                       <div><input class="form-control" type="number" name="SLOPE_0" placeholder="SLOPE_0" required="required"/></div>
                  </div>
                   <div class="input-group d-flex justify-content-between m-2">
                        <label for="slope_1" class="font-weight6">SLOPE_1</label>
                       <div><input class="form-control" type="number" name="SLOPE_1" placeholder="SLOPE_1" required="required"/></div>
                  </div>
                   <div class="input-group d-flex justify-content-between m-2">
                        <label for="slope_2" class="font-weight6">SLOPE_2</label>
                       <div><input class="form-control" type="number" name="SLOPE_2" placeholder="SLOPE_2" required="required"/></div>
                  </div>
                   <div class="input-group d-flex justify-content-between m-2">
                        <label for="CA_0" class="font-weight6">CA_0</label>
                       <div><input class="form-control" type="number" name="CA_0" placeholder="CA_0" required="required"/></div>
                  </div>
                   <div class="input-group d-flex justify-content-between m-2">
                        <label for="CA_1" class="font-weight6">CA_1</label>
                       <div><input class="form-control" type="number" name="CA_1" placeholder="CA_1" required="required"/></div>
                  </div>
                   <div class="input-group d-flex justify-content-between m-2">
                        <label for="CA_2" class="font-weight6">CA_2</label>
                       <div><input class="form-control" type="number" name="CA_2" placeholder="CA_2" required="required"/></div>
                  </div>
                   <div class="input-group d-flex justify-content-between m-2">
                        <label for="THAL_1" class="font-weight6">THAL_1</label>
                       <div><input class="form-control" type="number" name="THAL_1" placeholder="THAL_1" required="required"/></div>
                  </div>
                   <div class="input-group d-flex justify-content-between m-2">
                        <label for="THAL_2" class="font-weight6">THAL_2</label>
                       <div><input class="form-control" type="number" name="THAL_2" placeholder="THAL_2" required="required"/></div>
                  </div>
                   <div class="input-group d-flex justify-content-between m-2">
                        <label for="THAL_3" class="font-weight6">THAL_3</label>
                       <div><input class="form-control" type="number" name="THAL_3" placeholder="THAL_3" required="required"/></div>
                  </div>
                <div class="m-2">
                  <button type="submit" class="btn bg-blue text-white text-14 w-100 text-center">Predict</button>
                </div>
            </div>
    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

med-app/templates/diseases/kidney.html
{% extends "diseases/main.html" %}
{% block disease_body %}
    <div class="p-4" style="background: #F2F2F2">
        <div class="p-3" >
            <h4 class="font-weight8 text-center">Kidney Disease Prediction</h4>
            <h5 class="font-weight6 text-center">Please enter the patient details</h5>
        </div>
        <div class="d-flex justify-content-center">
            <div class="card"  style="width: 500px;">
                <div class="card-body">
                    <form action="{{ url_for('main.predictkidney')}}"  style="width: 470px;" method="post" class="text-14 form-inline">
                            <div class="tabcontent" id="new">
                                <div class="input-group d-flex justify-content-between m-2">
                                    <label for="bp" class="font-weight6">Blood Pressure</label>
                                    <div><input class="form-control" type="number" id="bp" name="Year" required="required" placeholder="Blood Pressure"></div>
                                </div>
                                <div class="input-group d-flex justify-content-between m-2">
                                    <label for="sg" class="font-weight6">Specific Gravity</label>
                                    <div><input class="form-control" type="number" step="any" id="sg" name="sg" required="required" placeholder="Specific Gravity"></div>
                                </div>

                                <div class="input-group d-flex justify-content-between m-2">
                                    <label for="al" class="font-weight6">Albumin</label>
                                    <div><input class="form-control" type="number" id="al" name="al" required="required" placeholder="Albumin"></div>
                                </div>

                                <div class="input-group d-flex justify-content-between m-2">
                                    <label for="su" class="font-weight6">Blood Sugar Level</label>
                                    <div><input class="form-control" type="number" id="su" name="su" required="required" placeholder="Blood Sugar Level"></div>
                                </div>

                                <div class="input-group d-flex justify-content-between m-2">
                                    <label for="rbc" class="font-weight6">Red Blood Cells Count</label>
                                    <div><input class="form-control" type="number" id="rbc" name="rbc" required="required" placeholder="Red Blood Cells Count"></div>
                                </div>

                                <div class="input-group d-flex justify-content-between m-2">
                                    <label for="pc" class="font-weight6">Pus Cell Count</label>
                                    <div><input class="form-control" type="number" id="pc" name="pc" required="required" placeholder="Pus Cell Count"></div>
                                </div>

                                <div class="input-group d-flex justify-content-between m-2">
                                    <label for="pcc" class="font-weight6">Pus Cell Clumps</label>
                                    <div><input class="form-control" type="number" id="pcc" name="pcc" required="required" placeholder="Pus Cell Clumps"></div>
                                </div>
                                <div class="m-2">
                                    <button type="submit" class="btn bg-blue text-white text-14 w-100 text-center">Predict</button>
                                </div>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}